english:
  0.0.1:
    basic: en_rpa_simple
    email: en_rpa_simple_email
    ner: xx_ent_wiki_sm
    reminder: en_rpa_simple_reminder
    schedule: en_rpa_simple_calendar
    spacy_md: en_core_web_md
    spacy_sm: en_core_web_sm
