name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  python:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file rpa-tomorrow.yml --name base
      - name: Install models for tests
        run: |
          $CONDA/bin/python -m spacy download xx_ent_wiki_sm
          $CONDA/bin/pip install -r requirements.txt
      - name: Format using black
        run: |
          $CONDA/bin/black --check . --diff --line-length=120
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          $CONDA/bin/flake8 . --count --ignore=N,W503 --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          $CONDA/bin/flake8 . --count --ignore=N,W503 --max-line-length=120 --statistics
      - name: Test with pytest
        run: |
          $CONDA/bin/pytest
